package com.purity.ecommerce;

import com.purity.ecommerce.models.*;
import com.purity.ecommerce.repositories.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;


@SpringBootApplication
public class ECommerceApplication {

	@Autowired
	private PasswordEncoder passwordEncoder;

	public static void main(String[] args) {
		SpringApplication.run(ECommerceApplication.class, args);
	}

	@Bean
	public CommandLineRunner initData(ProductRepository productRepository, CustomerRepository customerRepository,
									  OrderRepository orderRepository, CartRepository cartRepository, OrderItemRepository orderItemRepository){
		return (args) -> {

			Customer customer1 = new Customer("Customer1", "customer1@example.com", passwordEncoder.encode("password"), "Address 1");
			customerRepository.save(customer1);
			Customer customer2 = new Customer("Customer2", "customer2@example.com", passwordEncoder.encode("password"), "Address 2");
			customerRepository.save(customer2);
			Customer customer3 = new Customer("Customer3", "customer3@example.com", passwordEncoder.encode("password"), "Address 3");
			customerRepository.save(customer3);
			Customer admin = new Customer("admin", "admin3@example.com", passwordEncoder.encode("password"), "Address 3");
			customerRepository.save(admin);

			Product product1 = new Product("TRICLONE SKIN TECH HYDRATING", "DESCRPTION", "description1", 10.6, "Makeup", "HausLabs", 4, "C:/Users/Guest/Documents/MindHubJava/images/fadzhkjsilo_11LIGHTNEUTRAL_720x.webp", true);
			productRepository.save(product1);
			Product product2 = new Product("Product 1", "Description 1", "Short description 1", 10.6, "Makeup", "Brand 1", 4, "Image 1", true);
			productRepository.save(product2);
			Product product3 = new Product("Product 2", "Description 2", "Short description 2", 15.2, "Skincare", "Brand 2", 8, "Image 2", true);
			productRepository.save(product3);

			Cart cart1 = new Cart();
			cartRepository.save(cart1);
			Cart cart2 = new Cart();
			cartRepository.save(cart2);
			Cart cart3 = new Cart();
			cartRepository.save(cart3);

			customer1.setCart(cart1);
			customerRepository.save(customer1);
			customer2.setCart(cart2);
			customerRepository.save(customer2);
			customer3.setCart(cart3);
			customerRepository.save(customer3);

			cart1.addItem(new CartItem(2, product1));
			cart1.addItem(new CartItem(3, product3));
			cartRepository.save(cart1);

			cart2.addItem(new CartItem(3, product3));
			cart2.addItem(new CartItem(1, product2));

			cart3.addItem(new CartItem(1, product2));
			cart3.addItem(new CartItem(2, product1));

			OrderItem orderItem1 = new OrderItem(2, product1);
			OrderItem orderItem2 = new OrderItem(3, product3);
			OrderItem orderItem3 = new OrderItem(1, product2);
			OrderItem orderItem4 = new OrderItem(1, product1);
			OrderItem orderItem5 = new OrderItem(4, product3);
			OrderItem orderItem6 = new OrderItem(1, product2);

			orderItemRepository.save(orderItem1);
			orderItemRepository.save(orderItem2);
			orderItemRepository.save(orderItem3);

			PurchaseOrders purchaseOrders1 = new PurchaseOrders(LocalDateTime.now().minusDays(6), OrderStatus.DELIVERED, 500);
			purchaseOrders1.addOrderItem(orderItem1);

			PurchaseOrders purchaseOrders2 = new PurchaseOrders(LocalDateTime.now(), OrderStatus.PROCESSING, 150);
			purchaseOrders2.addOrderItem(orderItem2);

			PurchaseOrders purchaseOrders3 = new PurchaseOrders(LocalDateTime.now().minusDays(1), OrderStatus.SHIPPED, 300);
			purchaseOrders3.addOrderItem(orderItem3);

			customer1.addPurchaseOrder(purchaseOrders1);
			customer2.addPurchaseOrder(purchaseOrders2);
			customer3.addPurchaseOrder(purchaseOrders3);

			orderRepository.save(purchaseOrders1);
			orderItemRepository.save(orderItem1);
			orderRepository.save(purchaseOrders2);
			orderItemRepository.save(orderItem2);
			orderRepository.save(purchaseOrders3);
			orderItemRepository.save(orderItem3);

			purchaseOrders1.addOrderItem(orderItem4);
			purchaseOrders2.addOrderItem(orderItem5);
			purchaseOrders3.addOrderItem(orderItem6);

			customer1.addPurchaseOrder(purchaseOrders1);
			customer2.addPurchaseOrder(purchaseOrders2);
			customer3.addPurchaseOrder(purchaseOrders3);

			orderRepository.save(purchaseOrders1);
			orderItemRepository.save(orderItem4);
			orderRepository.save(purchaseOrders2);
			orderItemRepository.save(orderItem5);
			orderRepository.save(purchaseOrders3);
			orderItemRepository.save(orderItem6);
      
      /* Products */
			Product productBrushes1 = new Product("Ultra Plush Powder Brush", "Real Techniques Ultra Plush Powder Makeup Brush helps you create a flawless finish with its large, domed shape for all-over application. RT 201 powder brush has a plush large head for sheer application and a smooth, mattified finish. Best used with powder foundations, powder bronzers, and setting powders. Provides smooth, high-definition results with tapered bristles to help blend powders seamlessly. Extended aluminum ferrules that are light weight, easy to use, and color coded. 100% Cruelty-Free and Vegan. Flawless Results. Easy to clean with Real Techniques Brush Cleansing Gel or Spray. Long Lasting Makeup Application. UltraPlush Synthetic Bristles.", "Long Lasting Makeup Application.", 6.99, "brushes", "Real Techniques", 6, "https://i.imgur.com/xbcGA7J.jpg", true);
			Product productBrushes2 = new Product("Complexion Duo Brush", "2-IN-1 MAKEUP BRUSH: The e.l.f. Complexion Duo Brush is the only makeup brush you need for a flawless, airbrushed finish. This 2-in-1 brush is designed for the application of foundation and concealer. PRECISION APPLICATION: This face brush features a larger end for applying your foundation while the smaller end lends itself for precise application for the smaller areas you want to conceal. MULTI-USE: Ideal for use with liquids and powders. PERFECT PAIRING: e.l.f. Complexion Duo Brush is the only tool you need to apply Camo CC Cream Foundation and 16HR Camo Concealer. 100% VEGAN & SYNTHETIC BRISTLES: All e.l.f. brushes are made of synthetic, vegan fibers. All e.l.f. products are 100% cruelty-free and Vegan.", "Ideal for liquids and powders.", 7.50, "brushes", "e.l.f.", 14, "https://i.imgur.com/TVxloww.jpg", true);
			Product productBrushes3 = new Product("Flawless Face Brush", "CREATES A NATURAL LOOK: The e.l.f. Flawless Face Brush is a soft, synthetic brush that lets you apply product with the lightest touch for a soft, sheer, natural-looking effect. PRECISE APPLICATION: It has a slight point at the tip that fits nicely into the contours of the face for more precise placement. MULTI-USE & VERSATILE: This 2-sided brush allows you to use the flat side for all over application of powders, or the skinny side for blush and bronzer. 100% VEGAN & SYNTHETIC BRISTLES: All e.l.f. brushes are made of synthetic, vegan fibers. All e.l.f. products are 100% cruelty-free and Vegan. CARE INSTRUCTIONS: Cleanse regularly with the e.l.f. Cosmetics Daily Brush Cleaner (not live on Amazon right now) e.l.f. Cosmetics Brush Shampoo to maintain perfect color application and to increase the longevity of your brush.", "Made of synthetic, vegan fibers.", 4.20, "brushes", "e.l.f.", 10, "https://i.imgur.com/yC5b78Q.jpg", true);
			Product productBrushes4 = new Product("Retractable Face Brush", "The EcoTools Retractable Makeup Brush is designed with full, soft bristles for a versatile application of makeup on-the-go.\n" +
					"Designed for sensitive skin and versatile application of powder and bronzer.\n" +
					"Simply remove the cap and dab the brush in the makeup product.\n" +
					"Includes cap for mess-free storage.\n" +
					"Best used with powders and bronzers.\n" +
					"Beautifully soft bristles, for gentle makeup application.\n" +
					"Handcrafted with eco-friendly materials.\n" +
					"Made with synthetic Taklon bristles and sleek aluminum ferrules.\n" +
					"Cruelty-Free and Vegan - EcoTools products are never tested on animals.\n" +
					"Made with recycled materials - EcoTools believes in reducing waste by using recycled aluminum and plastic in our products.\n", "Flawless, airbrushed finish.", 7.50, "brushes", "EcoTools", 14, "https://i.imgur.com/mPIx14j.jpg", true);
			Product productBrushes5 = new Product("Duo Makeup Brush Kit", "The EcoTools Eye Enhancing Set is designed with 4 brush heads to shade, define, blend and smudge. Use the shade end to apply shadow all over the lid with the soft, tapered bristles. Define your eye look with the angled liner to line and enhance eye shape. Use the blend end to blend and blur shadow to eliminate streaks and harsh lines. Smudge shadow and liner along the lash line. Beautifully soft bristles, for gentle makeup application. Handcrafted with eco-friendly materials and lightweight bamboo handles. Made with synthetic Taklon bristles and sleek aluminum ferrules. 100% Cruelty Free and Vegan - EcoTools products are never tested on animals. Made with recycled materials - EcoTools believes in reducing waste by using recycled aluminum and plastic in our products.", "Beautifully soft bristles.", 4.90, "brushes", "EcoTools", 24, "https://i.imgur.com/kgpBkPZ.jpg", true);
			Product productBrushes6 = new Product("Skin Perfecting Brush", "The EcoTools Skin Perfecting Making Brush is designed with domed, angled bristles to blur imperfections for an airbrushed base. Works with powder, liquid, or cream foundations for a natural finish Domed shape allows for precise application. Soft construction creates an airbrushed-look foundation base. The skin perfecting brush is great to achieve low coverage for a more natural look. Beautifully soft bristles, for gentle makeup application. Handcrafted with eco-friendly materials and lightweight bamboo handles. Made with synthetic Taklon bristles and sleek aluminum ferrules. Cruelty Free and Vegan - EcoTools products are never tested on animals. Made with recycled materials - EcoTools believes in reducing waste by using recycled aluminum in our products.", "Low coverage, a more natural look.", 7.99, "brushes", "EcoTools", 33, "https://i.imgur.com/WgqvxET.jpg", true);
			Product productBrushes7 = new Product("Wonder Cover Brush", "The EcoTools Wonder Cover Complexion Foundation Makeup Brush is designed for full coverage in less time. Created with 100,000 bristles and an oval head for a natural looking coverage. Lightly dampen the bristles for a more sheer application. Can be used wet for a sheer application or dry for more coverage. With a simple sweep, camouflage common skin issues like rosacea, hyperpigmentation and blemishes. Best used with liquid or cream foundations for great results. Handcrafted with eco-friendly materials and lightweight bamboo handles. Made with synthetic Taklon bristles and sleek aluminum ferrules. 100% Cruelty Free and Vegan - EcoTools products are never tested on animals. Made with recycled materials - EcoTools believes in reducing waste by using recycled aluminum in our products.", "Camouflage common skin issues.", 6.20, "brushes", "EcoTools", 8, "https://i.imgur.com/tyjYsP4.jpg", true);
			Product productBrushes8 = new Product("Putty Bronzer Brush", "PERFECT FOR OUR PUTTY BRONZER: The best makeup brush for applying our Putty Bronzer! With its unique angled brush head and semi-stiff bristles, this brush is designed to pick up and distribute the perfect amount of product while hugging your cheeks. CONTOUR & HIGHLIGHT: Contour and highlight with control using the 100% synthetic, soft bristles, which blend the putty-to-powder formula into a smooth, even finish. FLAWLESS FINISH: Our Putty Bronzer brush easily picks up, distributes, and blends product for flawless, effortless application. Swirl brush into the putty bronzer. Then stipple and blend onto the hollows of your cheeks. 100% VEGAN & SYNTHETIC BRISTLES: All e.l.f. brushes & sponges are made of synthetic, vegan fibers. All e.l.f. products are 100% cruelty-free and Vegan. SKIN-LOVING INGREDIENTS: All e.l.f. products are made from skin-loving ingredients you want, minus the toxins you don’t—all at good-for-you prices. All e.l.f. products are 100% cruelty-free and Vegan.", "Flawless, effortless application.", 4.00, "brushes", "e.l.f.", 47, "https://i.imgur.com/qNSBKUP.jpg", true);
			Product productBrushes9 = new Product("Kabuki Face Brush", "This synthetic haired brush is soft and absorbent, making it perfect to use with wet or dry products. Allows for precise and controlled application of bronzer, powder, or highlighter. Compact design is ideal for travel and on-the-go use. For best results, clean or wipe brush daily. Cruelty-free, vegan and 100% free from Phthalates, Parabens, Nonylphenol, Ethoxylates, Triclosan, triclocarban.", "Soft and absorbent.", 7.00, "brushes", "e.l.f.", 19, "https://i.imgur.com/8wJPgPM.jpg", true);
			Product productBrushes10 = new Product("Domed Stipple Brush", "FLAWLESSLY BLENDS PRODUCT: This Domed Stipple Brush distributes product evenly by blurring product into the skin in a stippling process for a soft-focus “selfie ready” effect. VERSATILE USES: Our Domed Stipple Brush creates a seamless looking finish for foundation, concealer, and any other cream, liquid, or powder products. HOW TO USE: Dip the Selfie Ready Stipple Brush into product and apply to the face in a dotting or stippling motion.Use back and forth motions to blend. 100% VEGAN & SYNTHETIC BRISTLES: All e.l.f. brushes & sponges are made of synthetic, vegan fibers. All e.l.f. products are 100% cruelty-free and Vegan. SKIN-LOVING INGREDIENTS: All e.l.f. products are made from skin-loving ingredients you want, minus the toxins you don’t—all at good-for-you prices. All e.l.f. products are 100% cruelty-free and Vegan.", "Seamless looking finish.", 7.00, "brushes", "e.l.f.", 25, "https://i.imgur.com/31vbbyK.jpg", true);
			Product productBrushes11 = new Product("Mini Multitask Brush", "The Real Techniques Mini Multitask Brush is perfect for sweeping, swirling, and diffusing during your makeup application. Our RT 407 brush head has plush, tapered bristles for soft focus application. Features a full-sized head and compact handle, making this brush perfect for traveling. Use with powder blush, bronzer, or setting powder. Extended aluminum ferrules that are light weight, easy to use, and color coded. 100% Cruelty-Free and Vegan. Flawless Results. Easy to clean with Real Techniques Brush Cleansing Gel or Spray. Long Lasting Makeup Application. UltraPlush Synthetic Bristles.", "Easy to clean.", 4.20, "brushes", "Real Techniques", 4, "https://i.imgur.com/Jzx1BzF.jpg", true);
			Product productBrushes12 = new Product("Foundation Makeup Blender", "The Real Techniques Foundation Makeup Blender features small, dense bristles for blending & buffing for flawless coverage that's perfect for liquid, cream, & powder foundations. RT 213 features dense, domed bristles that blend and buff for even coverage, and can be used with bronzers. Provides smooth, high-definition results with small, dense bristles to blend and buff for flawless coverage. Best used with liquid, cream, or powder foundation. Blend, dab, and bluff for controlled blending. Light weight, easy to use, and color coded. 100% Cruelty-Free and Vegan. Easy to clean with Real Techniques Brush Cleansing Gel or Spray. UltraPlush Synthetic Bristles for flawless results. Long Lasting Makeup Application.", "Smooth, high-definition results.", 9.10, "brushes", "Real Techniques", 0, "https://i.imgur.com/hJCEnub.jpg", true);
			Product productBrushes13 = new Product("Bamboo Brush Set", "Pro Bamboo Makeup Brush set : Premium synthetic Laser cut superfine microfiber with wooden thick handles. Brush sizes and thickness varies. Include Powder foundation brush, Concealer brush, Eyelash eyebrow brush, Blush brush, Bronzer brush, Sponge applicator and Angled liner brush. Real wooden handles, Vegan hair and materials, Semi Soft synthetic bristles with natural cotton pouch which holds 7 makeup brushes. To get the best results, Rinse and clean with SHANY natural makeup brush cleanser before the first use, Brush instruction included in the box. Designed in the U.S.A by professional makeup artists. SHANY is a proud member of PETA. All of our products are cruelty free.", "Easy to clean.", 17.15, "brushes", "SHANY", 29, "https://i.imgur.com/SVubv4d.jpg", true);
			Product productBrushes14 = new Product("Travel Fantasy Brush Kit", "The Real Techniques Travel Fantasy Mini Brush kit includes 10 makeup brushes and a cosmetic bag for on-the-go glam. Includes: (1) RT 210 Mini Expert Concealer Brush, (1) RT 407 Mini Multitask Brush, (1) RT 206 Mini Contour Brush, (1) RT 406 Mini Medium Sculpting Brush, (1) RT 308 Mini Medium Shadow Brush, (1) RT 313 Mini Definer Brush, (1) RT 343 Mini Spoolie, (1) RT 332 Mini Smudge Brush, (1) RT 301 Mini Base Shadow Brush, (1) RT 307 Mini Shading Brush, and a Mini Makeup Bag. Makeup brushes can be used with any liquid, cream, and powder makeup products. Multiuse brushes best used with foundations, eyeshadows, concealers, blushes, bronzers, and more. Create any look you desire whether that’s bold and bright, or natural shimmer. Small brushes are easy to take with you wherever you go- whether it's at work or across the world! Store all your beauty tools and brushes in the travel cosmetic bag. UltraPlush custom-cut, synthetic bristles for superior product pickup and laydown. 100% Cruelty-Free and Vegan- Real Techniques products are never tested on animals. Designed for long-lasting makeup application.", "Easy to take with you.", 26.99, "brushes", "Real Techniques", 2, "https://i.imgur.com/JIjjYiz.jpg", true);
			Product productBrushes15 = new Product("Premium Brush Set", "【14-PIECE BRUSH COLLECTION】 Cover all your needs of all Your Makeup. Using BS-MALL blending brush, eyebrow brush, eyeshadow brushes and so on can give you results similar to makeup applied by a professional makeup artist!【FIT EVERY FACE】The eye makeup brushes come in a variety of shapes and sizes hence suitable for contouring & highlighting for every face shape.【Vegan & Cruelty-Free Bristles】 The bristles are well made of durable synthetic fiber - soft and silky nylon, ensuring long time use. All the makeup brushes are fine and dense, suitable for even the most sensitive skin. With a great holding power of powder, the brushes would be a good helper to create a flawless look.【STYLISH DESIGN】The 14 pcs makeup brush set looks very chic and fashionable with the most popular and elegant Rose Gold color , a must-have in your cosmetic bag.【Ideal For Gift】 Intended for makeup beginners and enthusiasts as the makeup brush kit is easy to use and superior in quality at an affordable price, a complete assortment to allow you to keep your makeup. Selected gift for mom, wife or female friends.", "Ideal for a gift.", 11.25, "brushes", "BS-MALL", 1, "https://i.imgur.com/KroTGll.jpg", true);
			Product productBrushes16 = new Product("Precious Metals Brush Set", "The EcoTools Brightening Eye Set has great eye brush essentials for you to achieve a chic eye look. The Precious Metals Brightening Eye Set includes (1) Angled Liner Brush, (1) Spoolie Brush, (1) Blending Crease Brush, (1) Crease Shadow Brush, and (1) Precision Smudge Brush. 4 essential makeup brushes that can be used in a variety of ways to make your eye look pop. Use our Brightening Eye set with liquid, cream or powder products. Get beautiful, bold eyeshadow looks using the Brightening Eye kit. The Brightening Eye Set is a part of our Precious Metals limited-edition collection which is inspired by earth’s natural metals. The set includes brushes made with 60% recycled aluminum- Aluminum is infinitely recyclable, helps reduce emissions, and is earth’s most abundant metal. The Brightening Eye kit is made with 100% recycled synthetic hair. Made with recycled materials - EcoTools believes in reducing waste by using recycled aluminum and plastic in our products. 100% Cruelty-Free and Vegan- EcoTools products are never tested on animals.", "Achieve a chic-eye look.", 11.90, "brushes", "EcoTools", 36, "https://i.imgur.com/p4UxFm0.jpg", true);

			Product productSkincare1 = new Product("Holy Hydration! Face Cream", "SPF 30 PROTECTION: Our best selling face cream now with SPF 30 sun protection you can wear daily! Hydrate and protect with this lightweight, ingredient-driven moisturizer that delivers lasting hydration, SPF 30 protection, and instantly absorbs into the skin, making it perfect for wearing under makeup. POWERFUL HYDRATION BOOST: This ultra-hydrating SPF face cream helps replenishes moisture for supple skin and evens out skin tone. Plus, the non-greasy formula instantly sinks into the skin for a smooth, super-soft feel and is great for any day. NOURISHES & PLUMPS SKIN: Key ingredients include Broad Spectrum SPF 30 to help protect the skin from harsh UVA/UVB rays, Hyaluronic Acid to lock in moisture for a plump complexion, Niacinamide to minimize pores & even out skin tone, and Peptides to promote collagen & improve skin texture. FOR EVERYONE: Good for normal, dry, combo and oily skin types. SKIN-LOVING INGREDIENTS: All e.l.f. products are made from skin-loving ingredients you want, minus the toxins you don’t—all at good-for-you prices. All e.l.f. products are 100% cruelty-free and Vegan.", "Hydrate and protect.", 12.00, "skincare", "e.l.f.", 17, "https://i.imgur.com/CyrIMXR.jpg", true);
			Product productSkincare2 = new Product("D.E.J. Face Cream", "An intensive skin-renewing moisturizer inspired by the Dermal-Epidermal Junction (DEJ), a critical factor in skin aging, that helps improve the visible signs of aging from multiple pathways and features. Prebiotic Innovation to promote a healthy Microbiome. Targets the appearance of fine lines and wrinkles. Visibly adds volume and plumps skin. Brightens and evens skin tone. Promotes a healthy Microbiome. Provides antioxidant benefits to help combat environmental stressors. Provides intense hydration with a lightweight feel. 1.7 oz w/pump", "Prebiotic Innovation.", 162.00, "skincare", "Revision", 31, "https://i.imgur.com/wdyqJ78.jpg", true);
			Product productSkincare3 = new Product("Firming Night Treatment", "This peptide-rich, age-defying cream provides intense short- and long-term moisturization while you sleep. Contains two peptides to reduce the look of fine lines and wrinkles. Includes Sodium Hyaluronate, which binds moisture to the skin. Alleviates dryness with Shea Butter and a blend of botanical extracts. Rehydrates, replenishes and brightens dull, dry skin. 1.0 oz jar Who benefits? Dry, sensitive and mature skin types.", "Alleviates dryness.", 90.00, "skincare", "Revision", 11, "https://i.imgur.com/pMRTfWX.jpg", true);
			Product productSkincare4 = new Product("Lumiquin Hand Cream", "Take time off your hands with this nighttime formula packed with powerful age-defying ingredients and antioxidants. Brightens the skin and minimizes the appearance of imperfections. Enhances skin's moisture level so hands look smoother. Supports skin's natural moisture barrier. 1.7 oz tube Who benefits? All skin types. Ideal for those with dry skin. How to Use Lumiquin is designed to be used once daily at night. To be effective, this product needs to be on the skin for several hours without hand washing. You can continue to use a regular hand cream during the day. Cleanse hands. Apply one pearl-sized drop onto the back of each hand before bedtime. For best results, apply sunscreen to hands during the day.", "For brighter hands.", 61.00, "skincare", "Revision", 42, "https://i.imgur.com/ssA4eVH.jpg", true);
			Product productSkincare5 = new Product("Happy Hydration Cream", "RICH, LUXE & CREAMY MOISTURIZER: e.l.f. Happy Hydration Cream is a rich, buttery face moisturizer that locks in moisture for ultra-hydrated skin, and feels like luxury on your face. NOURISHES & PLUMPS SKIN: This face cream easily blends into skin, helping it to retain moisture for lasting hydration while restoring youthful bounce in your complexion. ULTRA-HYDRATING INGREDIENTS: Infused with Vitamin B5 to soothe & calm, Hyaluronic Acid to lock in moisture for a plump complexion, and Niacinamide to help minimize pores & even out skin tone. FOR ALL SKIN TYPES: The e.l.f. Happy Hydration Cream is perfectly compatible with all skin types. SKIN-LOVING INGREDIENTS: All e.l.f. products are made from skin-loving ingredients you want, minus the toxins you don’t—all at good-for-you prices. All e.l.f. products are 100% cruelty-free and Vegan.", "Ultra-hydrating ingredients.", 12.00, "skincare", "e.l.f.", 29, "https://i.imgur.com/EVERTgP.jpg", true);
			Product productSkincare6 = new Product("Holy Hydration! Sleep Mask", "POWERFUL HYDRATION BOOST: Treat your skin to a good night’s sleep and wake up with a refreshed, hydrated complexion with e.l.f. Holy Hydration! Sleep Mask. This rich, creamy mask is your skin’s “reset button,” delivering a surge of moisture and replenishing dry and dehydrated skin. DUAL-USE FACE MASK: This ultra-hydrating mask can be used as a rinse-off product or as an overnight mask to promote a plumped up, radiant complexion, keep skin feeling soft and supple, and soothe & nourish skin while you sleep! NOURISHES & REPLENISHES SKIN: Key ingredients include Hyaluronic Acid to lock in moisture for a plump complexion, Ceramides to build up the skin’s moisture barrier, and Peptides to promote collagen and improve skin texture. FOR EVERYONE: Great for normal, dry, combination, and oily skin. Use 2-3x a week. SKIN-LOVING INGREDIENTS: All e.l.f. products are made from skin-loving ingredients you want, minus the toxins you don’t—all at good-for-you prices. All e.l.f. products are 100% cruelty-free and Vegan.", "Dual-use face mask.", 9.95, "skincare", "e.l.f.", 63, "https://i.imgur.com/fWPpkgj.jpg", true);
			Product productSkincare7 = new Product("Daily Hydration Moisturizer", "LOCK IN MOISTURE: The e.l.f. Daily Hydration Moisturizer is lightweight and deeply nourishing for smoother, suppler skin. ANTIOXIDANT-INFUSED: Infused with Aloe to help soothe the skin, Jojoba Oil & Shea Butter help hydrate the skin, Vitamin E to soften skin and Grapeseed Oil to even out skin tone. LIGHTWEIGHT, CREAMY FORMULA: Absorbs easily and nourishes the skin without weighing it down, revealing a naturally radiant complexion. FOR EVERYONE: Perfect for all skin types. SKIN-LOVING INGREDIENTS: All e.l.f. products are made from skin-loving ingredients you want, minus the toxins you don’t—all at good-for-you prices. All e.l.f. products are 100% cruelty-free and Vegan.", "Antioxidant-infused.", 8.00, "skincare", "e.l.f.", 44, "https://i.imgur.com/Gp8d0nd.jpg", true);
			Product productSkincare8 = new Product("SKIN Youth Boosting", "THE ULTIMATE ANTI-AGING SERUM: Introducing your skin’s e.l.f.ing game changer. The most powerful retinoid you can get without a ’script reduces the appearance of fine lines and wrinkles over time. CREATES A RADIANT COMPLEXION: With continued use, this results-driven night serum works to reveal rejuvenated, smooth and radiant skin. INFUSED WITH ANTIOXIDANTS: The potent formula is infused with a Retinoid + Antioxidant Complex to help reduce the appearance of fine lines and wrinkles and Hyaluronic Acid to help moisturize skin for a plump complexion. HOW TO USE: On clean skin, blend pea-sized amount onto your face and neck at night. Note that the amber color of the formula is a naturally occurring hue due to the potency of the retinoid complex. It will blend into the skin after application. SKIN-LOVING INGREDIENTS: All e.l.f. products are made from skin-loving ingredients you want, minus the toxins you don’t—all at good-for-you prices. All e.l.f. products are 100% cruelty-free and Vegan.", "Ultimate anti-aging serum.", 22.00, "skincare", "e.l.f.", 21, "https://i.imgur.com/Je2qBhO.jpg", true);
			Product productSkincare9 = new Product("Pure Skin Cleanser", "HYDRATING & GENTLE FACIAL CLEANSER: Our non-foaming cream cleanser gently cleanses to leave your skin feeling refreshed, hydrated, and squeaky clean. CLEANSES WITHOUT IRRITATION: Pure Skin Cleanser effectively removes dirt, oil and impurities without irritation. Gentle enough for all skin types- even sensitive skin. NOURISHING ESSENTIALS: Made with Oat Milk to nourish & soothe skin, Niacinamide to shrink pores & even out skin tone, Allanoin to soothe & skin, Ceramides to build up the skin's moisture barrier & Hyaluronic Acid to lock moisture for a plump complexion. HOW TO USE: Gently massage 1-2 pumps onto damp skin, rinse and pat dry. Use morning and night. Pairs well with e.l.f. Pure Skin Toner and e.l.f. Pure Skin Moisturizer. DERMATOLOGIST DEVELOPED: e.l.f. Pure Skin Cleanser is dermatologist-developed, fragrance-free, non-comedogenic, cruelty-free, and vegan.", "Hydrating and gentle.", 6.30, "skincare", "e.l.f.", 8, "https://i.imgur.com/OcZjlaz.jpg", true);
			Product productSkincare10 = new Product("Revitalift Moisturizer", "Revitalift Triple Power Daily Moisturizer is a fragrance free, anti-aging face moisturizer to visibly reduce wrinkles, firm and brighten skin in 1 week. Formulated with 3 of the top derm-recommended ingredients - Pro-Retinol, Hyaluronic Acid and Vitamin C. After use, skin feels softer, smoother and plumped with hydration - in 1 week, wrinkles are visibly reduced, firmness is improved and skin tone is brighter. Dermatology tested for safety, absorbs quickly, non-greasy, does not clog pores and suitable for sensitive skin - paraben free, mineral oil free, dye free, allergy tested, fragrance free. How to use - Apply to face and neck in the morning or night after cleansing and applying a serum- layers well under makeup.", "Absorbs quickly, non-greasy.", 22.00, "skincare", "L’Oréal Paris", 10, "https://i.imgur.com/mKQDJQv.jpg", true);
			Product productSkincare11 = new Product("True Match Lumi Glotion", "Glow Enhancing Make Up: Instantly hydrate and luminize your skin for an all over, natural glow with Lumi Glotion; This liquid face and body highlighter delivers an illuminating color tint to enhance your skin’s natural glow. Hydrating Makeup Highlighter: Our glow lotion is infused with glycerin and shea butter for all day hydration; Available in 4 shades for all skin tones, the glow drops can be worn alone, under foundation, or on target areas for a more luminous effect. Liquid Highlighter to Glow: Use Lumi Glotion illuminator to get a healthy, sun kissed glow with no sun; Try our complete line of bronzing drops, bronzers, luminizers, glow enhancing lotions. Because You're Worth It: Create the look you want with our full line of makeup including foundations, concealers, highlighter makeup, brow pencils, eyeshadow palettes, lipsticks and much more. L'Oreal Paris Beauty: A leading total beauty care company based in Paris, we offer innovative products and unique expertise from beauty experts in makeup, skin care, hair care, styling and hair color.", "Glow for your skin.", 13.00, "skincare", "L’Oréal Paris", 19, "https://i.imgur.com/rlvhS2E.jpg", true);
			Product productSkincare12 = new Product("Age Perfect Eye Cream", "Age Perfect Cell Renewal Eye Cream with Vitamin E is an anti-aging eye treatment that targets 5 signs of aging at once including dark circles, bags, puffiness, lines and crepey lids. Reveal millions of new cells day after day - made with a patented Antioxidant and Vitamin E to help recover skin's antioxidant reserves and boost its natural renewal process. This eye treatment absorbs quickly and provides 24 hours of hydration with no greasy or sticky finish. Dermatologist Tested - suitable for sensitive skin, this formula is allergy tested, fragrance free, paraben free and mineral oil free - suitable for contact lens wearers. Pair with New Age Perfect Cell Renewal Midnight Serum, a breakthrough anti-aging treatment that is preferred to the Number 1 Luxury Night Serum.", "24 hours of hydration.", 16.50, "skincare", "L’Oréal Paris", 26, "https://i.imgur.com/CniEu2d.jpg", true);
			Product productSkincare13 = new Product("Age Perfect Balm", "Age Perfect Hydra-Nutrition All-Over Balm is a silky balm for mature, very dry skin – soothes and rescues dry face, neck, chest, and hands – helps strengthen skin's ability to retain nourishing moisture and relieve dryness on face, neck, chest, and hands. All-Over Balm wraps skin in soothing moisture to soften skin that feels right and uncomfortable – beyond nourishment, skin is left looking more youthful with a healthy glow. Immediately, skin feels soothed, softer, smoother, more supple – by the end of the day, skin feels nourished, more comfortable, less tight – after 1 month of use, dry, fine lines appear reduced. Age Perfect Hydra-Nutrition All-Over Honey Balm with Manuka Honey Extract - Paraben Free, Mineral Oil Free, Non-Sticky, was Dermatologist tested for safety and is suitable for sensitive skin. For best results, use balm twice daily on clean skin - can be used over your daily moisturizer, ideal for face, neck, chest and hands.", "Soothes and rescues dryness.", 11.40, "skincare", "L’Oréal Paris", 34, "https://i.imgur.com/HDBMnsR.jpg", true);
			Product productSkincare14 = new Product("Creme Body", "Intensively Moisturizes: This NIVEA skin creme intensively moisturizes, nourishes and protects skin from that rough, dry feel. Provitamin B5 Enriched: This NIVEA moisturizer cream is enriched with Provitamin B5 to nourish dry skin. Multi-Use: NIVEA cream can be used as a body cream, hand cream and face cream for soft, smooth skin anytime. Great for Rough Spots: NIVEA Creme can be used all over the body, and is best for rough spots such as knees, feet, elbows and hands. Includes one (1) 16 ounce jar of NIVEA Creme Body, Face and Hand Moisturizing Cream.", "Intensively moisturizes.", 11.70, "skincare", "NIVEA", 4, "https://i.imgur.com/2X2cqJt.jpg", true);
			Product productSkincare15 = new Product("Skin Firming Body Lotion", "48-Hour Moisture: Specially formulated for darker skin tones to replenish nourishing moisture. Firmer Skin: Firms skin and improves skin elasticity in as little as two weeks(1) (with twice-daily application). Rich in Omegas: Skin firming body lotion contains Q10, natural Argan Oil (the 'liquid gold' of oils) rich in Omega 6 and 9 fatty acids Revitalizes and Nourishes: This NIVEA body lotion revitalizes and nourishes dry, ashy skin for 9 out of 10 women with melanin-rich skin(1). Long-Lasting Moisture: Gentle, non-greasy formula absorbs quickly and provides 48-hour moisture. Leave Your Skin Radiant: This moisturizing lotion leaves skin smooth, soft and radiantly beautiful. Skin Compatibility Tested: Dermatologically tested for skin compatibility. Trusted Brand: We use our 130 years of skincare expertise to carefully select high quality ingredients. Includes one (1) 16.9 fluid ounce bottle of NIVEA Skin Firming Melanin Beauty and Hydration Body Lotion with Q10 and Argan Oil.", "48-Hour Moisture.", 9.99, "skincare", "NIVEA", 44, "https://i.imgur.com/aLzidhP.jpg", true);
			Product productSkincare16 = new Product("Deep Clean Facial Cream", "7-fluid ounce tube of Neutrogena Deep Clean Cream Facial Cleanser to help improve dull complexion, for skin that looks and feels healthier. This daily facial cleanser is made with beta hydroxy acid and goes deep down into pores to dissolve dirt, oil and makeup, and wash away dead surface cells. Oil-free and alcohol-free, the face wash features a creamy, deep-cleansing lather that won't dry your skin. It's dermatologist-tested and rinses clean without leaving behind any pore-clogging residue, for fresher, healthier-looking skin. From a dermatologist recommended skincare brand, the deep clean face wash is non-comedogenic so it won't clog pores.", "Oil and alcohol-free.", 5.80, "skincare", "Neutrogena", 0, "https://i.imgur.com/owqsFsk.jpg", true);

			/*LIPS*/
			Product productLips1= new Product ("Color Block Lipstick", "What it is: A clean, handcrafted lipstick with high-impact color and supreme hydration, for all-day wear and care.How it works: Clean color, big impact. This full-coverage lipstick is handcrafted with custom pigments in organic castor seed oil—giving you four times the intensity with a creamy finish. For a bold, longwearing lip that stays smooth. In a range of ultra-wearable nudes, reds, and berries.What else you need to know: A balanced mix of classic shades including soft nudes, bold reds, and vibrant berries offers a solid block of color with even textures and smooth, creamy finishes."
			, "Soft oxblood, neutral undertones.", 28.00 , "lips" , "Ilia"  , 5, "https://i.imgur.com/630kNBj.jpg", true);
			Product productLips2= new Product("Color Block Lipstick", "What it is: A clean, handcrafted lipstick with high-impact color and supreme hydration, for all-day wear and care.How it works: Clean color, big impact. This full-coverage lipstick is handcrafted with custom pigments in organic castor seed oil—giving you four times the intensity with a creamy finish. For a bold, longwearing lip that stays smooth. In a range of ultra-wearable nudes, reds, and berries.What else you need to know: A balanced mix of classic shades including soft nudes, bold reds, and vibrant berries offers a solid block of color with even textures and smooth, creamy finishes. " , "Real red with cool undertones true red", 28.00, "lips","Ilia" , 3, "https://i.imgur.com/9n2GU34.jpg", true);
			Product productLips3= new Product("Multi-Stick", "What it is: A buildable wash of color for cheeks and lips—now with 12 swipe-and-go shades.How it works: This creamy cheek and lip color comes in a twist-up stick for easy application on the go. No tools required: Simply swipe and blend for skin that looks and feels alive. Keep it simple with your favorite Multi-Stick shade, or mix, match, and layer to create a customized look. Available in both natural and luminous finishes.What else you need to know:", " Mauve rose,at last", 36.00, "lips", "Ilia", 7, "https://i.imgur.com/4mHyksb.jpg", true);
			Product productLips4= new Product("Super Stay Vynil Ink" , " Meet Super Stay Vinyl Ink liquid lipstick for budge-resistant vinyl color and up to 16 hour wear. This longwear lipstick’s Color Lock formula defies smudging and transfer and provides an instant shine finish. Shake before applying on clean, dry lips. Now available in 10 additional Nude Shock shades inspired by the bold electric attitude of New York. Choose from a total of 20 high-impact vinyl shades for your every lip look", "Longwear liquid lipcolor ", 12.99, "lips", "Maybelline", 2, "https://i.imgur.com/H2vu1Lh.jpg", true);
			Product productLips5= new Product("Super Stay Vynil Ink " , "Meet Super Stay Vinyl Ink liquid lipstick for budge-resistant vinyl color and up to 16 hour wear. This longwear lipstick’s Color Lock formula defies smudging and transfer and provides an instant shine finish. Shake before applying on clean, dry lips. Now available in 10 additional Nude Shock shades inspired by the bold electric attitude of New York. Choose from a total of 20 high-impact vinyl shades for your every lip look ", "Longwear liquid lipcolor" , 12.99, "lips" , "Maybelline", 4, "https://i.imgur.com/fT92nXV.jpg", true);
			Product productLips6= new Product("Lifter Gloss", "Hydrated lips. Fuller look. This breakthrough formula with Hyaluronic Acid visibly smooths lip surface and enhances lip contour with high shine for hydrated, fuller looking lips. Plus, its XL wand transforms lips in an easy, one swipe application. Available in 20 shades.", "Lip gloss makeup with hyaluronic acid", 10.99, "lips","Maybelline", 7, "https://i.imgur.com/iZoUuZG.jpg", true);
			Product productLips7= new Product( "Super Stay Matte Ink", " Highly pigmented liquid matte lipstick that lasts up to 16 hours, now in reddish tones for a hotter look. You will love its arrow-type applicator that will make you outline your lips with greater precision. On top of everything, they are non-transferable, so you only have to worry about showing off red lips and feeling powerful.", " Exhilator Long-Lasting liquid lipstick", 7.98, "lips","Maybelline", 1, "https://i.imgur.com/RcYkI0M.jpg", true);
			Product productLips8= new Product(" Superstay Matte Ink Pinks", "Long-lasting liquid lipstick with a comfortable matte finish. Intense color in a single pass.", "Pink Pathfinder", 10.99, "lips", "Maybelline", 6, "https://i.imgur.com/jzIyVxZ.jpg", true);
			Product productLips9= new Product("Superstay Matte Ink Crayon", "Long Lasting Matte Lip Color: Maybelline Super Stay Ink Crayon in shade Accept A Dare, glides a rich layer of smudge and transfer resistant matte berry wine color across your lips. Lasts for up to 8 hours of wear. Use to line and fill your lips.Effortless Control: The built in sharpener of this award-winning matte lipstick keeps the tip ultra precise, so you can easily apply lip color wherever you are. Easily outline, shape, and color your lips in 1 swipe with no hassle and no fadingLet Your Lips Do the Talking: A matte lip color that glides on crayon-easy, so draw it on and wear it all day with no smudges or fading. Choose from our beautiful selection of longwear shades. The final step in your lip care routine.", "Lead the WAY", 10.99, "lips", "Maybelline", 3, "https://i.imgur.com/WQ2An1x.jpg", true);
			Product productLips10= new Product("Matte Lipstick", "A creamy rich Lipstick formula with high colour payoff in a no-shine matte finish.", "Intense Orange Brown (Matte)", 23.00, "lips", "MAC", 8, "https://i.imgur.com/hwIBrXk.jpg", true);
			Product productLips11= new Product("Powder Kidd Liquid Lip Color", "A liquid lipcolour with a whipped, mousse-like texture that delivers Soft-focus moisture-matte, comfortable colour with ten hours of hydration.","Deep wine",27.00, "lips", "MAC", 10, "https://i.imgur.com/BQ2BBdf.jpg", true);
			Product productLips12= new Product("Loqued Kiss Ink Lip Color", "A kissproof, transfer-proof and waterproof liquid lipstick with 24 hours of weightless wear and rich matte colour.", "Light Pinky Nude", 33.00, "lips", "MAC", 9, "https://i.imgur.com/4hAoyER.jpg", true);
			Product productLips13= new Product("Retro Matte Lipstick", " A long-wearing Lipstick formula with intense colour payoff and a completely matte finish.","Bright plum matte", 23.00, "lips", "MAC", 8, "https://i.imgur.com/M4P4eaT.jpg", true);
			Product productLips14= new Product("Matte Lipstick", "A creamy rich Lipstick formula with high colour payoff in a no-shine matte finish.", "Intense Brown",  23.00, "lips","MAC",5," https://i.imgur.com/aXh9Pjj.jpg", true);
			Product productLips15= new Product("Tinted Lip Conditioner","Infused with cocoa butter and jojoba oil to soften and vitamin e and pomegranate seed extract to heal and moisturise, hydrating, anti-aging benefits to the lips. a sheer touch of colour that can be built up in intensity when applied liberally. "," Lust For Life", 44.78, "lips", "Ilia", 0, "https://i.imgur.com/hLN2XKP.jpg", true);
			Product productLips16= new Product("Color Haze", "What it is: A game-changing cream blush and lip color in one—stays dewy on cheeks and transforms to a modern-matte finish on lips.How it works: A little color goes a long way. Made with jojoba and coconut oil, this two-in-one lip and cheek cream nourishes skin and blends out to a soft wash of color. With a precise metal applicator for fuss-free application on-the-go.What else you need to know:Size: 0.23 fl oz | 7 ml . About this shade: Universally flattering coral pink with warm undertones for subtle, face brightening flush.","Stutter (orange)", 32.00, "lips","Ilia", 6, "https://i.imgur.com/3yBFNr6.jpg", true);
			Product productEye1= new Product("Fullest Voluminizing Mascara", "What It Is: A clean volumizing mascara that wraps each lash in weightless, buildable volume without flaking, smudging, or irritating even the most sensitive eyes.What It Does: Fullest Volumizing Mascara thickens and defines lashes from root to tip with fullness you can’t miss. Clean, nourishing ingredients condition with every coat for lashes that look fuller, thicker, and healthier. The smudge-free, flake-free formula washes off easily with your favorite cleanser—no scrubbing, tugging, or heavy-duty makeup remover needed.Fullest Volumizing Mascara is ophthalmologist-tested, safe for sensitive eyes, and safe for contact lens wearers.", "Classic black", 28.00, "eyes", "Ilia", 9,"https://i.imgur.com/OFXAO9F.jpg", true);
			Product productEye2= new Product("The Necessary Eyeshadow", "What it is: Our 6 pan, Talc-free and cleanly formulated powder eyeshadow palettes have a buttery texture that allows for a smooth application.How it works: This new formula delivers high pigment and blends easily to a soft, wash of color with little fall out. Each of our palettes comes with an assortment of matte, satin and metallic finishes to achieve any look from day to night.","Cool toned matte", 40.00, "eyes", "Ilia", 5, "https://i.imgur.com/QSJjEvP.jpg", true);
			Product productEye3= new Product("Clean Line Gel Liner", "What it is: Our cleanly formulated (Carbon Black and Cyclomethicone-free) soft tip gel eyeliner.How it works: Clean Line Gel Liner glides effortlessly and allows you to blend out easily before setting. Once set, it stays put. Saturated and water resistant, this formula has the precision of a pencil with the ease of a gel.0.01 oz | 0.4 g", "Brown", 26.00, "eyes", "Ilia", 5,"https://i.imgur.com/ZVvlMrj.jpg", true);
			Product productEye4= new Product("Liquid Powder Eye Tint","What it is: A clean, cream-to-powder eyeshadow that dries down to a smudge-resistant finish. Choose from 16 matte and chromatic shades.How it works: Glides like a cream. Dries like a powder. Liquid Powder Eye Tint is a quick-dry eyeshadow that swipes on effortlessly and locks in without budging or fading. Blend the weightless, water-based formula for a diffused wash of color, or build it up for a bolder look that lasts.What else you need to know:Size: 0.12 fl oz | 3.5 ml","Warm Sand", 28.00, "eyes", "Ilia", 6, "https://i.imgur.com/gbsfCBw.jpg", true);
			Product productEye5= new Product("Micro-Tip Eyebrow Pencil", "The art of the arch—made easy. This foolproof pencil creates thin, hairlike strokes that blend into brows like magic. The micro-fine tip delivers the perfect amount of soft, buildable pigment that’s clinically proven to resist fading and budging throughout the day. Choose from eight versatile shades, each with a built-in spoolie for brushing and blending.", "For deep brown to black hair.", 24.00, "eyes", "Ilia", 6, "https://i.imgur.com/wrzx0lm.jpg", true);
			Product productEye6= new Product("Extra Dimension Eyeshadow", "SMOKY MAUVE Extra Dimension Eyeshadow", "Purple", 21.00, "eyes", "MAC", 5, "https://i.imgur.com/AyyVdhM.jpg", true);
			Product productEye7= new Product("Extra Dimension Eyeshadow", "Give a gift with flare! Wow your crowd this holiday season with a flashy collection bursting with glitter, shimmer and festive shine. Limited-edition colours for the eyes, lips and skin sparkle brightly, while curated kits burst with all-time favourites and all-new wonders. Each is wrapped in specially designed, flare-embossed, frosted-pink packaging. Like a firework, be one of a kind!. Eyes light up with five luminous shades of Extra Dimension Foil Eye Shadow. The lightweight formula has highly pigmented colour payoff with a shimmer-metallic finish. The results illuminate the day and scintillate at night. Shadow features an embossed burst design. All wrapped in specially designed, flare-embossed, frosted-pink packaging.", "Frosted Fireworks Firewerk The Room", 26.25, "eyes", "MAC", 3, "https://i.imgur.com/3TMSRMt.jpg", true);
			Product productEye8= new Product("In Extreme Dimension Lash", "A mascara with a lightweight, waterproof formula that lengthens, curls and volumizes lashes while conditioning them for softness and flexibility. The brush is designed to store the necessary amount of product in three reservoirs that allow as much as possible to be applied without leaving lumps or stains. The brush tip allows you to apply the product precisely to the lower lashes.", "A waterproof mascara.", 24.60, "eyes", "MAC", 4, "https://i.imgur.com/KZlytsG.jpg", true);
			Product productEye9= new Product("Eyebrows Styler", "Self-sharpening, rotating brow defining pencil – and now made with an updated waterproof formula. With an integrated eyebrow brush, it offers brushing along with maximum color precision in a dynamic, micro-fine pencil that emulates fine eyebrow hairs with each stroke for a perfect appearance. Confidently add what you need: shape, color and/or add intensity. Precision and accuracy, create your exact point for a surprising arch. Easy to take with you – no pencil sharpener needed.", "Eyebrow defining pencil", 23.00, "eyes", "MAC", 3, "https://i.imgur.com/bWeIFz0.jpg", true);
			Product productEye10= new Product("Eyeshadow Palette"," A well-edited palette of dusky rose hues offering countless colour combinations. It provides textures from matte to satin to frost for creating looks for both day and night. The saturated, soft and smooth shades are packaged in one pocket-sized compact for easy portability.", "Dusky Rose Times Nine",38.50, "eyes", "MAC", 3, "https://i.imgur.com/pVTbzFV.jpg", true);
			Product productEye11= new Product("Art Library Eyeshadow", "Bare your soul with the 12 intensely pigmented neutrals of Nude Model developed by M∙A∙C Pro Artists. The highly pigmented powder applies evenly and blends well. Can be used wet or dry. Available in a wide variety of textures and finishes.", "Intensely pigmented neutrals.",25.50,"eyes", "MAC", 7, "https://i.imgur.com/mDSODxo.jpg", true);
			Product productEye12= new Product("Palate Pleaser Eyeshadow", "Enjoy this incredible selection of eye color: a palette of 12 exclusive eyeshadows with Matte and Frost and Dazzleshadow Extreme textures in the best-selling shades. Its saturated eyeshadow formula stays on all day, lasting for eight hours and an intense color. Dazzleshadow Extreme's formula has a molten metallic finish that saturates in just one swipe and lasts for 12 hours. In limited edition packaging with bubbles and bows, all made with sustainability in mind.", "Limited edition palette.", 34.37, "eyes" , "MAC", 0, "https://i.imgur.com/L7dN844.jpg", true);
			Product productEye13= new Product("The Nudes Eyeshadow Palette", "12 shades, from subtle grays to electric blues, matte and satin textures. Infinite combinations, in a single palette! Be bold with the variety of shades to create infinite looks with a single palette. Ultra pigmented colors.", "Highly pigmented", 13.99, "eyes","Maybelline", 4, "https://i.imgur.com/5X6rtMj.jpg", true);
			Product productEye14= new Product("Total Temptation", "Total Temptation Maybelline Brow Pencil: Fill in brows with this must-have defining brow pencil, with a teardrop tip; Shape and blend with the brow brush, for a softly defined, natural-looking brow. Define your brow: No eye look is complete without Maybelline brow makeup - frame your eyes and fill in those brows with our precise micro brow pencil, with TattooStudio waterproof brow gel and arch-defining Total Temptation brow defining pencil", "Brow Definer Pencil, Soft Brown", 9.99, "eyes","Maybelline", 4, "https://i.imgur.com/MNxaNAy.jpg", true);
			Product productEye15= new Product("Instant Age Rewinds", "Concealer covers dark circles and bags, corrects imperfections, brightens the look and defines the face. Thanks to its formula with Goji Berries, it hydrates the eye area for up to 12 hours, treats and firms dark circles and bags. Its unique sponge applicator covers easily with precision and achieves coverage that does not dry out or crack. Correct, Contour and Brighten your face with Maybelline New York's Instant Age Rewinder.", "Instant age rewind.", 10.99, "eyes", "Maybelline",3,"https://i.imgur.com/pqJYvM4.jpg", true);



			productRepository.save(productBrushes1);
			productRepository.save(productBrushes2);
			productRepository.save(productBrushes3);
			productRepository.save(productBrushes4);
			productRepository.save(productBrushes5);
			productRepository.save(productBrushes6);
			productRepository.save(productBrushes7);
			productRepository.save(productBrushes8);
			productRepository.save(productBrushes9);
			productRepository.save(productBrushes10);
			productRepository.save(productBrushes11);
			productRepository.save(productBrushes12);
			productRepository.save(productBrushes13);
			productRepository.save(productBrushes14);
			productRepository.save(productBrushes15);
			productRepository.save(productBrushes16);

			productRepository.save(productSkincare1);
			productRepository.save(productSkincare2);
			productRepository.save(productSkincare3);
			productRepository.save(productSkincare4);
			productRepository.save(productSkincare5);
			productRepository.save(productSkincare6);
			productRepository.save(productSkincare7);
			productRepository.save(productSkincare8);
			productRepository.save(productSkincare9);
			productRepository.save(productSkincare10);
			productRepository.save(productSkincare11);
			productRepository.save(productSkincare12);
			productRepository.save(productSkincare13);
			productRepository.save(productSkincare14);
			productRepository.save(productSkincare15);
			productRepository.save(productSkincare16);

			productRepository.save(productLips1);
			productRepository.save(productLips2);
			productRepository.save(productLips3);
			productRepository.save(productLips4);
			productRepository.save(productLips5);
			productRepository.save(productLips6);
			productRepository.save(productLips7);
			productRepository.save(productLips8);
			productRepository.save(productLips9);
			productRepository.save(productLips10);
			productRepository.save(productLips11);
			productRepository.save(productLips12);
			productRepository.save(productLips13);
			productRepository.save(productLips14);
			productRepository.save(productLips15);
			productRepository.save(productLips16);


			productRepository.save(productEye1);
			productRepository.save(productEye2);
			productRepository.save(productEye3);
			productRepository.save(productEye4);
			productRepository.save(productEye5);
			productRepository.save(productEye6);
			productRepository.save(productEye7);
			productRepository.save(productEye8);
			productRepository.save(productEye9);
			productRepository.save(productEye10);
			productRepository.save(productEye11);
			productRepository.save(productEye12);
			productRepository.save(productEye13);
			productRepository.save(productEye14);
			productRepository.save(productEye15);


		};

	};

}
